name: Mi Primer Pipeline de Distribucion
on:
  push:
    branches: [ "main", "dev-carlos" ] # RETO 1: AÃ±ade la rama que corresponda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Construir Proyecto
        run: ./mvnw package -DskipTests # Generamos el .jar

      # RETO 2: Completar los datos para guardar el archivo
      - name: Guardar el archivo para descargar
        uses: actions/upload-artifact@v4
        with:
          name: mi-aplicacion-lista
          path: target/*.jar