name: Escaneo de Vulnerabilidades

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Descargar código
        uses: actions/checkout@v4

      # 2. Configurar Java 21 + caché de Maven
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'

      # 3. Dar permisos al wrapper
      - name: Dar permisos al wrapper de Maven
        run: chmod +x mvnw

#  Escaneo de vulnerabilidades con OWASP Dependency-Check 
      - name: Escaneo de vulnerabilidades (OWASP) run
        : ./mvnw -B org.owasp:dependency-check-maven:check