name: CI/CD Encadenado

on:
  push:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dar permisos al wrapper
        run: chmod +x mvnw

      - name: Ejecutar tests
        run: ./mvnw test

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: success()   # CD solo se ejecuta si CI ha ido bien
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Desplegar WAR
        run: echo "Aquí iría despliegue remoto por SCP"
